package com.iqvia.bhc.tab.service;

import java.util.Optional;

import com.iqvia.bhc.tab.db.entity.MessageContent;

/**
 * Schedule Task Service
 * @author TabTu
 */
public interface ScheduleTaskService {

	/**
	 * Schedule a message for printing on console
	 * @param schedule the trigger date time
	 * @param message the message will be displayed on console
	 * @return successfully scheduled a task
	 */
	boolean addScheduledMessage(String message, String schedule);
	
	/**
	 * Schedule a message for printing on console, identify with time zone
	 * @param schedule schedule the trigger date time
	 * @param timeZone modify the target time zone
	 * @param message the message will be displayed on console
	 * @return successfully scheduled a task
	 */
	boolean addScheduledMessage(String message, String schedule, String timeZone);
	
	/**
	 * Find a message by message key from database
	 * @param msgId generated by MD5<64> + BASE64
	 * @return message content
	 */
	Optional<MessageContent> findMessage(String msgId);
}

